In [1]:
import numpy as np
import pandas as pd

In [2]:
book=pd.read_csv('C:/Users/rohi/Desktop/Data Science/Assignment/My Assisgnments/Assignment_9_Recommendation system/book.csv',encoding='latin-1')
#encoding

In [3]:
book.head()

Unnamed: 0  User.ID                                               Book  \
0           1   276726                                Classical Mythology   
1           2   276729                                       Clara Callan   
2           3   276729                               Decision in Normandy   
3           4   276736  Flu: The Story of the Great Influenza Pandemic...   
4           5   276737                             The Mummies of Urumchi   

   Book.Rating  
0            5  
1            3  
2            6  
3            8  
4            6

In [11]:
book_d=book.iloc[:,0:]


In [12]:
book_d.head()

User.ID                                               Book  Book.Rating
0   276726                                Classical Mythology            5
1   276729                                       Clara Callan            3
2   276729                               Decision in Normandy            6
3   276736  Flu: The Story of the Great Influenza Pandemic...            8
4   276737                             The Mummies of Urumchi            6

In [13]:
#df.rename(columns={"OldName":"NewName"})

book_d=book_d.rename(columns={'User.ID':'userID'})

In [14]:
book_d=book_d.rename(columns={'Book.Rating':'rating'})

In [15]:
book_d.head()

userID                                               Book  rating
0  276726                                Classical Mythology       5
1  276729                                       Clara Callan       3
2  276729                               Decision in Normandy       6
3  276736  Flu: The Story of the Great Influenza Pandemic...       8
4  276737                             The Mummies of Urumchi       6

In [17]:
len(book_d.userID.unique())#no.of unique users in the dataset

2182

In [18]:
len(book_d.Book.unique())

9659

In [22]:
book_d.drop_duplicates(subset=None,keep='first',inplace=False)

userID                                               Book  rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[9998 rows x 3 columns]

In [25]:
np.where(book_d.index.duplicated())

(array([], dtype=int64),)

In [27]:
#user_book_df = book_DF.pivot_table(index='userid',
                                 #columns='book',
                                 #values='rating').reset_index(drop=True)

user_data=book_d.pivot_table(index='userID',columns='Book',values='rating').reset_index(drop=True)

In [28]:
user_data.head()

Book   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                      NaN                                         NaN   
1                      NaN                                         NaN   
2                      NaN                                         NaN   
3                      NaN                                         NaN   
4                      NaN                                         NaN   

Book   Repairing PC Drives &amp  '48  \
0                           NaN  NaN   
1                           NaN  NaN   
2                           NaN  NaN   
3                           NaN  NaN   
4                           NaN  NaN   

Book  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                   NaN                       
1                                                   NaN                       
2                                                   NaN                       
3                                                   NaN                       
4                                                   NaN                       

Book  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                   NaN              
1                                                   NaN              
2                                                   NaN              
3                                                   NaN              
4                                                   NaN              

Book  01-01-00: A Novel of the Millennium  1,401 More Things That P*Ss Me Off  \
0                                     NaN                                 NaN   
1                                     NaN                                 NaN   
2                                     NaN                                 NaN   
3                                     NaN                                 NaN   
4                                     NaN                                 NaN   

Book  10 Commandments Of Dating  100 Great Fantasy Short, Short Stories  ...  \
0                           NaN                                     NaN  ...   
1                           NaN                                     NaN  ...   
2                           NaN                                     NaN  ...   
3                           NaN                                     NaN  ...   
4                           NaN                                     NaN  ...   

Book  Zora Hurston and the Chinaberry Tree (Reading Rainbow Book)  \
0                                                   NaN             
1                                                   NaN             
2                                                   NaN             
3                                                   NaN             
4                                                   NaN             

Book  \Even Monkeys Fall from Trees\ and Other Japanese Proverbs  \
0                                                   NaN            
1                                                   NaN            
2                                                   NaN            
3                                                   NaN            
4                                                   NaN            

Book  \I Won't Learn from You\: And Other Thoughts on Creative Maladjustment  \
0                                                   NaN                        
1                                                   NaN                        
2                                                   NaN                        
3                                                   NaN                        
4                                                   NaN                        

Book  \More More More,\ Said the Baby  \O\ Is for Outlaw  \
0                                 NaN                NaN   
1                        

In [31]:
user_data.index=book_d.userID.unique()#rearrange the data

In [32]:
user_data

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
276726                   NaN                                         NaN   
276729                   NaN                                         NaN   
276736                   NaN                                         NaN   
276737                   NaN                                         NaN   
276744                   NaN                                         NaN   
...                      ...                                         ...   
162107                   NaN                                         NaN   
162109                   NaN                                         NaN   
162113                   NaN                                         NaN   
162121                   NaN                                         NaN   
162129                   NaN                                         NaN   

Book     Repairing PC Drives &amp  '48  \
276726                        NaN  NaN   
276729                        NaN  NaN   
276736                        NaN  NaN   
276737                        NaN  NaN   
276744                        NaN  NaN   
...                           ...  ...   
162107                        NaN  NaN   
162109                        NaN  NaN   
162113                        NaN  NaN   
162121                        NaN  NaN   
162129                        NaN  NaN   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
276726                                                NaN                       
276729                                                NaN                       
276736                                                NaN                       
276737                                                NaN                       
276744                                                NaN                       
...                                                   ...                       
162107                                                NaN                       
162109                                                NaN                       
162113                                                NaN                       
162121                                                NaN                       
162129                                                NaN                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
276726                                                NaN              
276729                                                NaN              
276736                                                NaN              
276737                                                NaN              
276744                                                NaN              
...                                                   ...              
162107                                                NaN              
162109                                                NaN              
162113                                                NaN              
162121                                                NaN              
162129                                                NaN              

Book    01-01-00: A Novel of the Millennium  \
276726                                  NaN   
276729                                  NaN   
276736                                  NaN   
276737                                  NaN   
276744                                  NaN   
...                                     ...   
162107                                  NaN   
162109                                  NaN   
162113                                  NaN   
162121                                  NaN   
162129                                  NaN   

Book    1,401 More Things That P*Ss Me Off  10 Commandments Of Dating  \
276726                                 NaN                        NaN   
276729                           

In [33]:
#Impute those NaNs with 0 values
user_data.fillna(0, inplace=True)

In [34]:
user_data

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
276726                   0.0                                         0.0   
276729                   0.0                                         0.0   
276736                   0.0                                         0.0   
276737                   0.0                                         0.0   
276744                   0.0                                         0.0   
...                      ...                                         ...   
162107                   0.0                                         0.0   
162109                   0.0                                         0.0   
162113                   0.0                                         0.0   
162121                   0.0                                         0.0   
162129                   0.0                                         0.0   

Book     Repairing PC Drives &amp  '48  \
276726                        0.0  0.0   
276729                        0.0  0.0   
276736                        0.0  0.0   
276737                        0.0  0.0   
276744                        0.0  0.0   
...                           ...  ...   
162107                        0.0  0.0   
162109                        0.0  0.0   
162113                        0.0  0.0   
162121                        0.0  0.0   
162129                        0.0  0.0   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
276726                                                0.0                       
276729                                                0.0                       
276736                                                0.0                       
276737                                                0.0                       
276744                                                0.0                       
...                                                   ...                       
162107                                                0.0                       
162109                                                0.0                       
162113                                                0.0                       
162121                                                0.0                       
162129                                                0.0                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
276726                                                0.0              
276729                                                0.0              
276736                                                0.0              
276737                                                0.0              
276744                                                0.0              
...                                                   ...              
162107                                                0.0              
162109                                                0.0              
162113                                                0.0              
162121                                                0.0              
162129                                                0.0              

Book    01-01-00: A Novel of the Millennium  \
276726                                  0.0   
276729                                  0.0   
276736                                  0.0   
276737                                  0.0   
276744                                  0.0   
...                                     ...   
162107                                  0.0   
162109                                  0.0   
162113                                  0.0   
162121                                  0.0   
162129                                  0.0   

Book    1,401 More Things That P*Ss Me Off  10 Commandments Of Dating  \
276726                                 0.0                        0.0   
276729                           

In [ ]:
#Calculating Cosine Similarity between Users

In [35]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [36]:
user_sim=1-pairwise_distances(user_data.values,metric='cosine')#cosine base simillarity

In [37]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)

In [40]:
#Set the index and column names to user ids 
user_sim_df.index =book_d.userID.unique()
user_sim_df.columns =book_d.userID.unique()

In [41]:
user_sim_df

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     1.0     0.0     0.0     0.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  ...  162085  162091  162092  162095  162103  162107  \
276726     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     1.0   
162109     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

        162109  162113  162121  162129  
276726     0.0     0.0     0.0     0.0  
276729     0.0     0.0     0.0     0.0  
276736     0.0     0.0     0.0     0.0  
276737     0.0     0.0     0.0     0.0  
276744     0.0     0.0     0.0     0.0  
...        ...     ...     ...     ...  
162107     0.0     0.0     0.0     0.0  
162109     1.0     0.0     0.0     0.0  
162113     0.0     1.0     0.0     0.0  
162121     0.0     0.0     1.0     0.0  
162129     0.0     0.0     0.0     1.0  

[2182 rows x 2182 columns]

In [42]:
user_sim_df.index

Int64Index([276726, 276729, 276736, 276737, 276744, 276745, 276747, 276748,
            276751, 276754,
            ...
            162085, 162091, 162092, 162095, 162103, 162107, 162109, 162113,
            162121, 162129],
           dtype='int64', length=2182)

In [43]:
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [44]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [45]:
#Most Similar Users
user_sim_df.idxmax(axis=1)[0:10]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
276745    276726
276747    276726
276748    161677
276751    276726
276754    276726
dtype: int64

In [50]:
book_d[(book_d['userID']==276736) | (book_d['userID']==276726)]

userID                                               Book  rating
0  276726                                Classical Mythology       5
3  276736  Flu: The Story of the Great Influenza Pandemic...       8

In [51]:
user_1=book_d[book_d['userID']==276736]

In [52]:
user_2=book_d[book_d['userID']==276726]

In [53]:
user_1.Book

3    Flu: The Story of the Great Influenza Pandemic...
Name: Book, dtype: object

In [54]:
user_2.Book

0    Classical Mythology
Name: Book, dtype: object

In [55]:
pd.merge(user_1,user_2,on='Book',how='outer')

userID_x                                               Book  rating_x  \
0  276736.0  Flu: The Story of the Great Influenza Pandemic...       8.0   
1       NaN                                Classical Mythology       NaN   

   userID_y  rating_y  
0       NaN       NaN  
1  276726.0       5.0

A person whose userid is 276736, I would like to recommend him books like "Classical Mythology" . For pearson whose userid is 276726, I recommend him the books read by person whose userid is 276736. These are the best recommendations for books reading. Similarly, we can recommend to other peoples.